config/routes.rb
Rails.application.routes.draw do
  root "items#index"
  devise_for :users, controllers: {
    sessions: "users/sessions"
  }
  devise_scope :user do
    get "users/sign_out" => "users/sessions#destroy"
  end

  resources "users", only: %i[destroy]
  resources :items, only: %i[index create update destroy] do
      patch :daiso, on: :member
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  validates :name, length: { in: 0..15 }, presence: true, uniqueness: { scope: :user_id }, format: { with: /\A[^ |　]+\z/}
  # validates :value, presence: true, format: { with: /\A[^0A-Za-z]+/i, message: '"数字" をご入力下さい (※又は、"0"のみの入力は出来ません)。'}
  # validates :number, presence: true, format: { with: /\A[^A-Za-z]+/i, message: '"数字" をご入力下さい'}

  scope :desc_order, -> { order(created_at: :desc) }

  def rev_name
    case self.daiso
    when nil
      self.daiso = self.name.to_s
      self.save
    else
      self.update(daiso: nil)
    end
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  has_many :items, dependent: :destroy
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :timeoutable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery with: :null_session
end

app/controllers/concerns/index_form.rb
module IndexForm
    extend ActiveSupport::Concern
    
    included do
        def form_content
            @items = Item.where(user_id: current_user.id).desc_order

            @total = 0
            @items.each do |item|
                @total += item.value * item.number
            end
        end
    end

end

app/controllers/items_controller.rb
class ItemsController < UsersController
  before_action :authenticate_user!
  before_action :detail, only: %i[daiso destroy]
  #form_contentの処理呼び出し。↓
  include IndexForm

  def index
    @item = Item.new
    form_content
  end

  def create
    @item = Item.new(item_params)
    if @item.save
      redirect_to action: :index
    else
      form_content
      render "index"
    end
  end

  def update
    @item = Item.where(id: params[:items].keys)
    @item.each do |item|
      item.number = params[:items]["#{item.id}"].to_i
      item.save
    end
    redirect_to action: :index
  end

  def daiso
    @detail.rev_name
    redirect_to action: :index
  end

  def destroy
    @detail.destroy
    redirect_to action: :index
  end

  private

  def item_params
    params.require(:item).permit(:name, :value, :number).merge(user_id: current_user.id)
  end

  def detail
    @detail = current_user.items.find_by(id: params[:id])
  end

end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    def destroy
        @user = User.find(params[:id])
        @user.destroy
        redirect_to "/users/sign_in"
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/index.html.erb
<div class="container">
  <!-- 新規登録 -->
  <div class="container__form">
    <%= form_with(model: @item, id: "formnew", class: "container__form__tag", local: true) do |f| %>
      <p class="container__form__tag__item container__form__tag__element">
        <%= f.label :name, :品名 %>
        <%= f.text_field :name, placeholder: "空白はご遠慮下さい", class: "placeholder" %>
        <!-- カスタムエラーテンプレート↓ -->
        <%= render partial: "layouts/errors_messages", locals: { element: :item, message: :name } %>
      </p>

      <p class="container__form__tag__value container__form__tag__element">
        <%= f.label :value, :価格 %>
        <%= f.text_field :value, placeholder: "半角数字で入力下さい", class: "placeholder", oninput: "value = value.replace(/[^0-9]+/i, '')" %>
        <!-- カスタムエラーテンプレート↓ -->
        <%= render partial: "layouts/errors_messages", locals: { message: :value } %>
      </p>

      <p class="container__form__tag__number container__form__tag__element">
        <%= f.label :number, :個数 %>
        <%= f.text_field :number, placeholder: "半角数字で入力下さい", class: "placeholder", oninput: "value = value.replace(/[^0-9]+/i, '')" %>
        <!-- カスタムエラーテンプレート↓ -->
        <%= render partial: "layouts/errors_messages", locals: { message: :number } %>
      </p>
    <% end %>
    <p class="container__form__send">
      <input type="submit" value="品登録" form="formnew" name="commit" data-disable-with="送信中" >
    </p>
  </div>
  <!-- 合計金額  -->
  <div class="container__total_wrap">
    <table border="" class="container__total_wrap__tbl">
      <tr>
        <th class="container__total_wrap__tbl__total_th">精算予定</th>
        <td class="container__total_wrap__tbl__total_td"><span id="total_price" ><%= @total %></span> 円</td>
      </tr>
    </table>
    <input type="submit" class="container__total_wrap__updatesend updatesend" name="commit" value="更新" form="update">
  </div>
  <div class="container__index">
    <!-- 登録一覧、更新。 -->
    <% if @items.present? %>
      <%= form_with( url: "/items/:id", method: :patch, id: :update, local: true) do |f| %>
        <table border="" class="container__index__index_tbl">
          <% @items.each do |item| %>
            <tr>
              <th class="container__index__index_tbl__index_th">品名</th>
                <td class="index_td">
                  <%= link_to "#{item.name}", "/items/#{item.id}/daiso", method: :patch, class: :daiso, data: { dsname: "#{item.daiso}" } %>
                </td>
              <th class="container__index__index_tbl__index_th">単価</th>
                <td class="container__index__index_tbl__index_th__value unit_price" data-price="<%= item.value %>"> <%= item.value %>円</td>
              <th class="container__index__index_tbl__index_th">個数</th>
                <td class="index_number_td">
                  <%= f.text_field "items[#{item.id}]", value: "#{item.number}", class: "counter#{item.id} amount",
                    oninput: "value = value.replace(/[^0-9]+/i, '')" %> 点<br>
                </td>
              <th id="spinner_button">
                <input type="button" value="＋" class="btnspinner" data-cal="1" data-target=".counter<%= item.id %>"> 
                <input type="button" value="－" class="btnspinner" data-cal="-1" data-target=".counter<%= item.id %>">
              </th>
              <th id="delete">
                <%= link_to "[削除]", "/items/#{item.id}", method: :delete, data: { confirm: "'#{item.name}' 削除しても宜しいですか？" } %>
              </th>
              <th>
                <input type="button" class="reset" name="reset" value=" 未 " data-from=".counter<%= item.id %>" data-bill_val="<%= item.value %>">
              </th>
            </tr>
          <% end %>
        </table>
      <% end %>
    <% end %>
    <div class="container__index__bill_div">
      <input type="submit" class="container__index__bill_div__aft_mvUpBtn updatesend" name="commit" value="更新" form="update">
      <table border="" class="container__index__bill_div__tbl">
        <tr>
          <th id="container__index__bill_tbl__bill_th">会計<br><span id="bill_sp">0</span><br>円です</th>
        </tr>
      </table>
    </div>
  </div>
</div>

<%= javascript_pack_tag 'shoppingindex.js' %>
<%= javascript_pack_tag 'intersection_observer.js' %>

app/views/items/practice.js.erb
// document.getElementById("kajaa").addEventListener("click", function(){ 
// // var mydiv = document.getElementById("mydiv");
// // mydiv.innerHTML = "<h3>h1をh3へ変更しました！<h3>";
// // }, false);


// ---------------------------------------------------------------------------------------------------------


// const push = document.getElementById("push");

// push.addEventListener("click", function(e){
//   const look = document.getElementById("h").innerHTML;

//   if(look=="変更前"){
//     document.getElementById("h").innerHTML = "<h2>変更されました</h2>";
//   }else if(look=="<h2>変更されました</h2>"){
//     document.getElementById("h").innerHTML = "変更前";
//   }
// });

// ---------------------------------------------------------------------------------------------------------

document.getElementById("str").addEventListener("keyup", function(e){ // ← "str" IDの要素(タグ)を取得してそれの "イベント発動条件" を "change" とする。
  var str = document.getElementById("str"); // "str" を変数化する。
  str.nextSibling.textContent = str.value;  // ID "str" の要素内の文字列を "str.value (※〇〇.valueプラウザ上のフォームの値に指定するという意味)" に当てはめる。
});

app/views/layouts/_errors_messages.html.erb
<% if @item.errors.messages[message].any? %>
  <span class="container__form__tag__element__error"><%= @item.errors.messages[message][0] %></span>
<% end %>

app/views/layouts/_header.html.erb
<header class="header">
  <div class="header__bar">
        <h1 class="header__bar__title-logo">shopping memo</h1>
    <% if user_signed_in? %>
        <p class="header__bar__daiso-item"><span class="spr_col">この文字色</span>: "daiso" 商品</p>
        <div class="header__bar__acount">
          <p class="header__bar__acount__logout">
            <%= link_to "ログアウト", "users/sign_out", data: { confirm: "ログアウトで宜しいですか？" } %>
          </p>
          <p class="header__bar__acount__user-delete">
            <%= link_to "アカウント削除", user_path(current_user.id), method: :delete, data: { confirm: "アカウントを削除しますか？" } %>
          </p>
        </div>
    <% end %>
    <hr class="header__bar__hr">
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Shopping2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <%# モバイル表示用 %>	
    <meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>  <%# ←マニュフェストファイルの指定 →application.css(マニュフェストファイル) %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>  <%# ←マニュフェストファイルの指定 application.js(マニュフェストファイル) %>
      <!-- favicon -->
    <link rel="icon" href="/app/assets/images/favicon.ico">
      <!-- windows version別 -->
    <link rel=”icon” type=”image/vnd.microsoft.icon” href="/app/assets/images/favicon.ico">
    <link rel=”shortcut icon” href=”/app/assets/images/favicon.ico>
      <!-- iphone -->
    <link rel="apple-touch-icon" sizes="180x180" href="/app/assets/images/apple-touch-icon.png">
      <!-- android -->
    <link rel="icon" type="image/png" href="/app/assets/images/android-touch-icon.png" sizes="192x192">
    <!-- css -->
  </head>

  <body>
    <%= render "users/shared/notifications" %>
    <%= render "layouts/header" %>
    <%= yield %>
    
    <script src="https://code.jquery.com/jquery-3.6.0.min.js" integrity="sha256-/xUj+3OJU5yExlq6GSYGSHk7tPXikynS7ogEvDej/m4=" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<div class="links_component">
  <%- if controller_name != 'sessions' %>
    <%= link_to "ログインはこちら", new_session_path(resource_name) %><br />
  <% end %>

  <%- if devise_mapping.registerable? && controller_name != 'registrations' %>
    <%= link_to "新規登録", new_registration_path(resource_name) %><br />
  <% end %>

  <%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
    <%= link_to "パスワードをお忘れですか?", new_password_path(resource_name) %><br />
  <% end %>

  <%- if user_signed_in? && devise_mapping.confirmable? && controller_name != 'confirmations' %>
    <%= link_to "本登録設定メールを再送信", new_confirmation_path(resource_name) %><br />
  <% end %>
</div>

app/views/users/shared/_notifications.html.erb
<div class="notifications">
    <% flash.each do |key, value| %>
        <%= content_tag(:div, value, class: "#{key}") %>
    <% end %>
</div>